### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by loong-L** [BHUPC90/.github#2]
BHUPC：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入BHUPC学习！

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
<你的名字>

**Comment by Ruixi-rebirth** [comment]
欢迎
